### ISSUE TITLE
The GET method is not supported for route admin/developer-gate. Supported methods: POST.

### ISSUE THREAD

**Issue by momostafa** [tomatophp/filament-artisan#1]
Hi,

after install gui page redirects to mysite.test/admin/developer-gate with below error

The GET method is not supported for route admin/developer-gate. Supported methods: POST.

After Commenting out below traits the page renders and works fine. 

```php
<?php

namespace TomatoPHP\FilamentArtisan\Pages;

use Filament\Pages\Page;
use Illuminate\Support\Facades\App;
use TomatoPHP\FilamentArtisan\Http\Controllers\GuiController;
// use TomatoPHP\FilamentDeveloperGate\Traits\DeveloperGateLogoutAction;
// use TomatoPHP\FilamentDeveloperGate\Traits\InteractWithDeveloperGate;

class Artisan extends Page
{

    // use InteractWithDeveloperGate;
    // use DeveloperGateLogoutAction;
``` 

those traits are needed?

Thanks for another nice plugin

**Comment by 3x1io** [comment]
okay you need to add `DeveloperGatePlugin` to your panel

```php
->plugin(/TomatoPHP/FilamentDeveloperGate/FilamentDeveloperGatePlugin::make())
```

**Comment by JamieCee20** [comment]
> okay you need to add `DeveloperGatePlugin` to your panel
> 
> ->plugin(/TomatoPHP/FilamentDeveloperGate/FilamentDeveloperGatePlugin::make())

Just added this, I still get the same error

**Comment by catative** [comment]
1.  Publish config file by use this command: `php artisan vendor:publish --tag="filament-artisan-config"`
2. Change `'developer_gate' => true` to  `'developer_gate' => false` in `config/filament-artisan.php` 
3. Clear cache if necessary: `php artisan optimize:clear`
4. Check Artisan plugin URL: `http://you-domain.com/PANEL/artisan` (not `http://you-domain.com/admin/developer-gate`)
